# number-srd = 0001
# title-srd = Two Sum
# filename-srd = 0001_Two_sum.py
# difficulty-srd = easy
# language-srd = python
# tags-srd = ARRAY, HASHTABLE
# leetcodelink-srd = https://leetcode.com/problems/two-sum/
# acceptancerate-srd = 49.1%
# notes-srd = 
# end-srd = 